= Process overview
include::ROOT:partial$include.adoc[]

The main steps in developing a service include:

. <<_specify_service_interface_and_domain_model>>
. <<_implement_components>>
. <<_create_unit_tests>>
. <<_package_service>>
. <<_run_locally>>
. <<_deploy_to_akka_serverless>>


[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

The main components of a Kalix service are:

* Stateful https://docs.kalix.io/reference/glossary.html#entity[Entities]
* Stateless https://docs.kalix.io/reference/glossary.html#action[Actions]
* https://docs.kalix.io/reference/glossary.html#view[Views], which return the state of multiple instances of a stateful entity.

The service interface and the domain data model (for Entities), are contained in individual `.proto` files, as https://grpc.io[gRPC] descriptors. Separating the service interface and data model in different files allows you to evolve them independently.

The gRPC definitions in `.proto` files describe the external interface, messages, and events. From the `.proto` files, the gRPC CLI (`protoc`), generates the code framework for remote procedure calls, data access, and serialization. Take a look at xref:javascript:proto.adoc[Writing gRPC descriptors] for more information about defining messages and events.

TIP: Kickstart a project using the xref:javascript:kickstart.adoc[JavaScript code generation tool].

[#_implement_components]
== Implement components

ifdef::todo[TODO: link to glossary for Replicated Entity in main docs]

Stateful services can implement https://docs.kalix.io/reference/glossary.html#value_entity[Value Entity], https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entity], or Replicated Entity components. Stateless services implement Actions. Typically, a stateful service should only have one Entity type, but can also include Actions.

=== Actions

Actions are stateless functions that can be triggered by gRPC or HTTP calls. They can also subscribe to published events, and they can send commands to other services based on the events they receive. For more information about writing actions see xref:javascript:actions.adoc[Implementing Actions].

=== Entities

Stateful services encapsulate business logic in in Value Entities, Event Sourced Entities, or Replicated Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.

TIP: To learn more about Kalix entities see xref:javascript:value-entity.adoc[Implement a Value Entity], xref:javascript:eventsourced.adoc[Implement an Event Sourced Entity], and xref:javascript:replicated-entity.adoc[Implement a Replicated Entity].

To update multiple Entities from a single command use forwarding and effects. 

TIP: For more information see xref:javascript:forwarding.adoc[Forwarding and effects in JavaScript].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

For more details and examples take a look at the following topics:

* xref:javascript:value-entity.adoc[Implementing Value Entities]
* xref:javascript:eventsourced.adoc[Implementing Event Sourced Entities]
* xref:javascript:replicated-entity.adoc[Implementing Replicated Entities]
* xref:javascript:entity-eventing.adoc[Subscribing to a journal]
* xref:javascript:topic-eventing.adoc[Publishing and subscribing to topics on a broker]

[#_create_unit_tests]
== Create unit tests

It is good practice to write unit tests as you implement your services. The JavaScript kickstart codegen project packages Mocha and Chai and is configured for test-driven development.

[#_package_service]
== Package service

Use a Docker image to package your service and any of its dependencies. See the following pages for more information:

* https://docs.kalix.io/setting-up/index.html#_containers[Installing Docker]
* https://docs.kalix.io/quickstart/cr-value-entity-javascript.html#_package_and_deploy_your_service[Packaging with Docker]
* https://docs.kalix.io/projects/container-registries.html[Configuring registries]

[#_run_locally]
== Run locally

You can test and debug your services by
https://docs.kalix.io/services/running-locally.html[running them locally] before deploying to Kalix.

== Deploy to Kalix

After testing locally, deploy your service to Kalix using the CLI or the Console. The following pages provide information about deployment:

* https://docs.kalix.io/projects/index.html[Working with Kalix projects]
* https://docs.kalix.io/services/deploy-service.html#_deploy[Deploying a packaged service]
* https://docs.kalix.io/quickstart/cr-value-entity-javascript.html#_package_and_deploy_your_service[Example of how to package and deploy a service]
