= Process overview
include::ROOT:partial$include.adoc[]

The main steps in developing a service include:

. <<_specify_service_interface_and_domain_model>>
. <<_implement_components>>
. <<_create_unit_tests>>
. <<_package_service>>
. <<_run_locally>>
. <<_deploy_to_akka_serverless>>


[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

The main components of an Akka Serverless service are:

* Stateful xref:reference:glossary.adoc#entity[Entities]
* Stateless xref:reference:glossary.adoc#action[Actions]
* xref:reference:glossary.adoc#view[Views], which return the state of multiple instances of a stateful entity.

The service interface and the domain data model (for Entities), are contained in individual `.proto` files, as https://grpc.io[gRPC] descriptors. Separating the service interface and data model in different files allows you to evolve them independently.

The gRPC definitions in `.proto` files describe the external interface, messages, and events. From the `.proto` files, the gRPC CLI (`protoc`), generates the code framework for remote procedure calls, data access, and serialization. Take a look at xref:javascript:proto.adoc[Writing gRPC descriptors] for more information about defining messages and events.

TIP: Kickstart a project using the xref:javascript:kickstart.adoc[JavaScript code generation tool].

[#_implement_components]
== Implement components

Stateful services can implement xref:reference:glossary.adoc#value_entity[Value Entity] or xref:reference:glossary.adoc#event_sourced_entity[Event Sourced Entity] components. Stateless services implement Actions. Typically, a stateful service should only have one Entity type, but can also include Actions.

=== Actions

Actions are stateless functions that can be triggered by gRPC or HTTP calls. They can also subscribe to published events, and they can send commands to other services based on the events they receive. For more information about writing actions see xref:javascript:actions.adoc[Implementing Actions].

=== Entities

Stateful services ecapsulate business logic in in Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time. 

TIP: To learn more about Akka Serverless entities see xref:javascript:value-entity.adoc[Implement a Value Entity] and xref:javascript:eventsourced.adoc[Implement an Event Sourced Entity].

To update multiple Entities from a single command use forwarding and effects. 

TIP: For more information see xref:javascript:forwarding.adoc[Forwarding and effects in JavaScript].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

For more details and examples take a look at the following topics:

* Event Sourced Entities in xref:javascript:eventsourced.adoc[JavaScript]
* Value Entities in xref:javascript:value-entity.adoc[JavaScript]
* Subscribe to a journal in xref:javascript:entity-eventing.adoc[JavaScript]
* Set up pub/sub for xref:javascript:topic-eventing.adoc[JavaScript]

[#_create_unit_tests]
== Create unit tests

It is good practice to write unit tests as you implement your services. The JavaScript kickstart codegen project packages Mocha and Chai and is configured for test-driven development. For implementation details see the xref:tutorial:node-cart-test.adoc#_ii_add_unit_tests[Shopping cart tutorial - Create unit tests] topic.

[#_package_service]
== Package service

Use Docker to package your service and any of its dependencies. See the following pages for more information:

* xref:getting-started:set-up-development-env.adoc#_docker[Installing Docker]
* xref:deploying:docker.adoc[]
* xref:deploying:registries.adoc[]
* xref:tutorial:node-cart-package-deploy.adoc[Example of how to package a service]

[#_run_locally]
== Run locally

You can test and debug your services by
xref:javascript:run-locally.adoc[running them locally] before deploying to Akka Serverless.

== Deploy to Akka Serverless

After testing locally, deploy your service to Akka Serverless using the CLI or the Console. The following pages provide information about deployment:

* xref:getting-started:projects.adoc[]
* xref:deploying:deploying.adoc[]
* xref:tutorial:index.adoc[Examples of how to deploy]
