= JavaScript/TypeScript Protobuf SDK
:page-supergroup-javascript-typescript: Language

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Kalix JavaScript SDK offers an idiomatic JavaScript language SDK for writing components. This page describes prerequisites for JavaScript development and basic requirements for a development project.

NOTE: Lightbend provides Tier 1 support for the JavaScript SDK. See https://docs.kalix.io/faq/index.html#_what_languages_are_supported[an explanation of support tiers] for more information.

Your development project needs to include the Kalix JavaScript SDK and logic to start the gRPC server. You define your components in gRPC descriptors and use `protoc` to compile them. Finally, you implement business logic for service components.

To simplify this process, the JavaScript xref:kickstart.adoc[code generation tool] produces a pre-built project with descriptors and implementations.

If you prefer to begin by exploring a fully implemented Kalix service, you can try one of our comprehensive https://www.kalix.io/developer/experience/typescript/[use cases] or a https://docs.kalix.io/quickstart/index.html#_typescriptprotobuf[Quickstart application].

== Prerequisites

The following are required to develop services in JavaScript:

Node:: Kalix requires at least Node {minimum_node_version}. You will find links to download Node https://nodejs.org/dist/latest-v14.x/[here {tab-icon}, window="new"].

Build tool:: Kalix does not require a specific build tool. However, for a seamless out-of-the-box experience, npm and Yarn are recommended, though you have the flexibility to choose your preferred tool.

Docker:: Kalix requires https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] {minimum_docker_version} for building your service images. Most popular build tools have plugins that assist in building Docker images.

Since Kalix is based on gRPC, you need a protoc compiler to compile gRPC protobuf descriptors. The SDK provides helper scripts to automatically download the `protoc` compiler for your platform and compile your project.

== Development project requirements

The following examples show how to install the SDK to build your services with npm or Yarn. The code generation tools include a Kalix xref:kickstart.adoc[code generation tools] that generates the recommended project structure, including a `package.json` file with the necessary references.

NOTE: The code generation tools do more than just provide a starter project, after you modify a `.proto` file, they will generate code stubs for the elements you changed or added.

If you are starting from scratch, you will need to add configuration and code to:

* <<_add_sdk_libraries>>
* <<_define_grpc_descriptors_and_compile>>
* <<_create_and_start_the_grpc_server>>

== Add SDK libraries

Once you have the prerequisites, you need to add the `@kalix-io/kalix-javascript-sdk` package to your service development project, which can be done by running:

[source,sh,subs="attributes+"]
----
npm install @kalix-io/kalix-javascript-sdk@{kalix-javascript-sdk-version} --save-exact
----

To create a basic service, you need to include the `kalix` package dependencies in your project, define gRPC descriptors in `.proto` files and reference them in your project, compile the `.proto` files, and have logic to start the gRPC server in your source code.

The following shows a minimal `package.json` configuration for a shopping cart service project:


[source,json,subs="attributes+"]
----
{
  "name": "shopping-cart",
  "version": "0.1.0",
  "dependencies": {
    "@kalix-io/kalix-javascript-sdk": "{kalix-javascript-sdk-version}"
  },
  "scripts": {
    "prestart": "compile-descriptor shoppingcart.proto",
    "start": "node index.js"
  }
}
----

=== Define gRPC descriptors and compile

Descriptors for gRPC are defined in `protobuf` files. You can place `protobuf` files in your project wherever you like, for example, in the root directory, or in a directory named `protos`. In the `package.json` example, above we've placed the service descriptor in a file in the root folder called `shoppingcart.proto`. See xref:proto.adoc[] for more details.

=== Pre-compile the protobuf descriptor set

The gRPC descriptor is serialized to binary using the Protobuf https://developers.google.com/protocol-buffers/docs/techniques#self-description[`FileDescriptorSet` message type]. Kalix requires that you pre-compile this descriptor using `protoc`. We provide a utility that does this for you. It downloads the `protoc` binary for your platform, and runs it with the necessary arguments and include paths. You can run the utility manually, or we recommend adding it as a script to the build.

To run the utility manually, invoke `node_modules/@kalix-io/kalix-javascript-sdk/bin/compile-descriptor.js`.


Or, add a `prestart` script to your `npm` build:

[source,json]
----
{
  "scripts": {
    "prestart": "compile-descriptor my-descriptor.proto"
  }
}
----

=== The compile-descriptor utility

Multiple protobuf files can be passed to the `compile-descriptor` utility. You can also pass any arguments accepted by `protoc`. For example, if you are importing files from other directories, you can add those directories as an include path by adding `-Ipath/to/protobuf/dir`.

By default, the descriptor is written to `user-function.desc`, if you wish to change this, you can set `--descriptor_set_out=my-descriptor.desc`. Note that if you output the descriptor to a different path, you will also need to pass that custom path to the constructor of the `kalix` class when you got to instantiate it.

=== Create and start the gRPC server

Use the link:{attachmentsdir}/api/classes/Kalix.html[`Kalix`{tab-icon}, window="new"] class, add one or more link:{attachmentsdir}/api/interfaces/Component.html[`Components`{tab-icon}, window="new"] to it, and then invoke link:{attachmentsdir}/api/classes/Kalix.html#start[`start`{tab-icon}, window="new"], like so:

[.tabset]
JavaScript::
+
[source,js,indent=0]
----
include::example$test/gettingstarted/index.js[tag=start]
----

TypeScript::
+
[source,ts,indent=0]
----
include::example$test/gettingstarted/index.ts[tag=start]
----

If you created your protobuf file descriptor set at a different location to the default of `user-function.desc`, you can configure that here:

[.tabset]
JavaScript::
+
[source,js,indent=0]
----
include::example$test/gettingstarted/index.js[tag=custom-desc]
----

TypeScript::
+
[source,ts,indent=0]
----
include::example$test/gettingstarted/index.ts[tag=custom-desc]
----

For all options available on the `Kalix` class, see link:{attachmentsdir}++/api/module-kalix.Kalix.html#~options++[`Kalix~options`{tab-icon}, window="new"].

== What's next

This section includes information on the following topics:

* xref:javascript:proto.adoc[]
* xref:eventsourced.adoc[Event Sourced Entities]
* xref:javascript:value-entity.adoc[]
* xref:javascript:views.adoc[]
* xref:forwarding.adoc[Forwarding and effects]
* xref:javascript:actions-publishing-subscribing.adoc[]
* xref:serialization.adoc[Serialization]
* link:{attachmentsdir}/api/index.html[JavaScript API docs{tab-icon}, window="new"]
