= Writing gRPC descriptors

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

Kalix SDKs support `protobuf` descriptors in the https://developers.google.com/protocol-buffers/docs/proto3[Proto3 {tab-icon}, window="new-tab"] Protocol Buffers language. You define command messages, data associated with Entities, and events in `.proto` files. From these definitions, the gRPC compiler creates client and server side code that saves work for you and enables Kalix to serialize message data.

Note that Value Entities and Event Sourced Entities are slightly different based upon codegen requirements. Other than the code generation annotations, the proto files are materially equivalent for the same use-case. See the following examples which show the difference.

[.tabset]
Event Sourced Entity::
+
--
[source, proto]
----
include::example$js-eventsourced-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_state]
----
--
Value Entity::
+
--
[source, proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_state]
----
--

We recommend that you define your service API and events and data associated with components separately. This allows business logic to evolve independently of the public interface. This page walks you through elements in an example `shoppingcart_api.proto` file and the associated `shoppingcart_domain.proto` file.

== The service API proto file

The first line of an example `shoppingcart_api.proto` file defines the version of Protocol Buffer syntax:

.proto/shoppingcart_api.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_syntax]
----

The following imports provide Kalix and gRPC functionality:

.proto/shoppingcart_api.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_imports]
----

The `package` specifies a namespace for this `proto` file and its imports--names must be unique within each namespace:

.proto/shoppingcart_api.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_package]
----

=== Messages

==== Messages for entities

Each input message for an Entity that is input to a RPC command, *must* be associated with an Entity key, so that Kalix can identify which entity the message is for. In the example, this includes `AddLineItem`, `RemoveLineItem`, and `GetShoppingCart` where the `user_id` is the `(akkaserverless.field).entity_key`.

Kalix extracts the value of these fields in order to route messages to the right Entity. If more than one field is specified as an Entity key, the fields are concatenated together. Kalix serializes Entity keys to strings.

.proto/shoppingcart_api.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_messages]
----

To use a multi-field key, add the `entity_key` notation to each field. For example, this `SomeMessage` element defines both `first_field` and `second_field` as part of the key:

[source,proto]
----
message SomeMessage {
  string first_field = 1 [(akkaserverless.field).entity_key = true];
  string second_field = 2 [(akkaserverless.field).entity_key = true];
----

==== Generated entity keys

In some cases, you may wish to generate an Entity key, this is typically done when an RPC method creates an entity, and the key is a surrogate key. To indicate to Kalix that an Entity key should be generated, the incoming message must not have any `(akkaserverless.field).entity_key` annotated field. Instead, the rpc method should be annotated with `(akkaserverless.method).entity.key_generator`, for example:

[source,proto]
----
rpc CreateCart(CreateCartRequest) returns (CreateCartResponse) {
  option (akkaserverless.method).entity.key_generator = VERSION_4_UUID;
};
----

This will generate a version 4 (random) UUID for the Entity. Only version 4 UUIDs are currently supported for generated Entity keys.

It will often be necessary to access the generated entity key from inside the entities code. This can be done using the link:{attachmentsdir}/api/module-akkaserverless.EntityContext.html#entityId[entityId{tab-icon}, window="new"] property on the passed in context.

=== Service

This section of the `.proto` file declares the API of the service itself, along with each function or method and their parameters and return types. When a command is received for a given Entity key, Kalix will establish a gRPC streamed call to the service implementation using that Entity's type's protocol--if one isn't already established. Any commands received for the Entity key will be sent through that call.

The `AddItem` and `RemoveItem` methods have no return value (the `Empty` type).

See <<_transcoding_http>> for an explanation of the HTTP annotations.

.proto/shoppingcart_api.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_service]
----
<1> See <<_transcoding_http>> below
<2> See <<_transcoding_http>> below
<3> See <<_transcoding_http>> below

== The domain proto file

The `shoppingcart_domain.proto` file specifies the state and messages for an Event Sourced Entity. It defines the gRPC version:

.proto/shoppingcart_domain.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_syntax]
----

It only needs to include the import for `akkaserverless/annotations.proto`:

.proto/shoppingcart_domain.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_imports]
----

The following defines the `ShoppingCart` Entity state:

.proto/shoppingcart_domain.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_state]
----

It includes the messages that define the entity state:

.proto/shoppingcart_domain.proto
[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_domain.proto[tag=proto_messages]
----

[#_transcoding_http]
== Transcoding HTTP

Kalix supports transcoding gRPC to HTTP/JSON, using the Google transcoding annotations described https://cloud.google.com/endpoints/docs/grpc/transcoding[here]. You can use transcoding to consume your Entities' gRPC interfaces using HTTP/JSON.

In the example below, the optional transcoding of the service to bind the various endpoints to HTTP is highlighted with annotations.

[source,proto]
----
include::example$js-valueentity-shopping-cart/proto/shoppingcart_api.proto[tag=proto_service]
----
<1> This extra annotation specifies that you can call this endpoint using the POST method with the URI `/cart/\{cart_id}/items/add`, where `\{cart_id}` is the actual id of the cart you want to use.
<2> A URL that accepts a POST method to remove a line item.
<3> A more complex example where the first `get` URI retrieves the whole cart, and the second retrieves the items in the cart.
