/*
 * Copyright 2021-2023 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// re-export types generated by proto-loader-gen-types to be namespaced together
// use `__Output` types for incoming messages, which will have defaults applied

export { ProtoGrpcType as Descriptor } from '../generated/proto/discovery';

export { DiscoveryHandlers as Handlers } from '../generated/proto/kalix/protocol/Discovery';

export { ProxyInfo__Output as ProxyInfo } from '../generated/proto/kalix/protocol/ProxyInfo';

export { Spec } from '../generated/proto/kalix/protocol/Spec';
export { ServiceInfo } from '../generated/proto/kalix/protocol/ServiceInfo';
export { Component } from '../generated/proto/kalix/protocol/Component';
export { GenericComponentSettings } from '../generated/proto/kalix/protocol/GenericComponentSettings';
export { EntitySettings } from '../generated/proto/kalix/protocol/EntitySettings';
export { ReplicatedEntitySettings } from '../generated/proto/kalix/protocol/ReplicatedEntitySettings';

export { UserFunctionError__Output as UserFunctionError } from '../generated/proto/kalix/protocol/UserFunctionError';
export { _kalix_protocol_UserFunctionError_SourceLocation__Output as SourceLocation } from '../generated/proto/kalix/protocol/UserFunctionError';
export { _kalix_protocol_UserFunctionError_Severity as Severity } from '../generated/proto/kalix/protocol/UserFunctionError';

export { IdentificationInfo__Output as IdentificationInfo } from '../generated/proto/kalix/protocol/IdentificationInfo';
