/*
 * Copyright 2021-2023 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// re-export types generated by proto-loader-gen-types to be namespaced together
// use `__Output` types for incoming messages, which will have defaults applied

export { ProtoGrpcType as Descriptor } from '../generated/proto/replicated_entity';

export { ReplicatedEntitiesDefinition as Definition } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntities';

import { ReplicatedEntitiesHandlers } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntities';
export { ReplicatedEntitiesHandlers as Handlers };

export type Handle = ReplicatedEntitiesHandlers['Handle'];
export type Call = Parameters<Handle>[0];

export { ReplicatedEntityStreamIn__Output as StreamIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityStreamIn';
export { ReplicatedEntityInit__Output as Init } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityInit';
export { ReplicatedEntityDelta__Output as DeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityDelta';
export { ReplicatedCounterMapEntryDelta__Output as CounterMapEntryDeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedCounterMapEntryDelta';
export { ReplicatedMapEntryDelta__Output as MapEntryDeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedMapEntryDelta';
export { ReplicatedMultiMapEntryDelta__Output as MultiMapEntryDeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedMultiMapEntryDelta';
export { ReplicatedRegisterDelta__Output as RegisterDeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedRegisterDelta';
export { ReplicatedRegisterMapEntryDelta__Output as RegisterMapEntryDeltaIn } from '../generated/proto/kalix/component/replicatedentity/ReplicatedRegisterMapEntryDelta';
export { Any__Output as AnyIn } from '../generated/proto/google/protobuf/Any';

export { ReplicatedEntityStreamOut as StreamOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityStreamOut';
export { ReplicatedEntityReply as Reply } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityReply';
export { ReplicatedEntityDelta as DeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedEntityDelta';
export { ReplicatedCounterMapEntryDelta as CounterMapEntryDeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedCounterMapEntryDelta';
export { ReplicatedMapEntryDelta as MapEntryDeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedMapEntryDelta';
export { ReplicatedMultiMapEntryDelta as MultiMapEntryDeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedMultiMapEntryDelta';
export { ReplicatedRegisterDelta as RegisterDeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedRegisterDelta';
export { ReplicatedRegisterMapEntryDelta as RegisterMapEntryDeltaOut } from '../generated/proto/kalix/component/replicatedentity/ReplicatedRegisterMapEntryDelta';
export { Any as AnyOut } from '../generated/proto/google/protobuf/Any';
