/*
 * Copyright 2021 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// re-export types generated by proto-loader-gen-types to be namespaced together
// use `__Output` types for incoming messages, which will have defaults applied

export { ProtoGrpcType as Descriptor } from '../generated/proto/value_entity';

export { ValueEntitiesDefinition as Definition } from '../generated/proto/kalix/component/valueentity/ValueEntities';

import { ValueEntitiesHandlers } from '../generated/proto/kalix/component/valueentity/ValueEntities';
export { ValueEntitiesHandlers as Handlers };

export type Handle = ValueEntitiesHandlers['Handle'];
export type Call = Parameters<Handle>[0];

export { ValueEntityStreamIn__Output as StreamIn } from '../generated/proto/kalix/component/valueentity/ValueEntityStreamIn';
export { ValueEntityInit__Output as Init } from '../generated/proto/kalix/component/valueentity/ValueEntityInit';
export { ValueEntityInitState__Output as InitState } from '../generated/proto/kalix/component/valueentity/ValueEntityInitState';
export { Any__Output as AnyIn } from '../generated/proto/google/protobuf/Any';

export { ValueEntityStreamOut as StreamOut } from '../generated/proto/kalix/component/valueentity/ValueEntityStreamOut';
export { ValueEntityReply as Reply } from '../generated/proto/kalix/component/valueentity/ValueEntityReply';
export { Any as AnyOut } from '../generated/proto/google/protobuf/Any';
