/*
 * Copyright 2021-2023 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// re-export types generated by proto-loader-gen-types to be namespaced together
// use `__Output` types for incoming messages, which will have defaults applied

export { ProtoGrpcType as Descriptor } from '../generated/proto/view';

export { ViewsDefinition as Definition } from '../generated/proto/kalix/component/view/Views';

import { ViewsHandlers } from '../generated/proto/kalix/component/view/Views';
export { ViewsHandlers as Handlers };

export type Handle = ViewsHandlers['Handle'];
export type Call = Parameters<Handle>[0];

export { ViewStreamIn__Output as StreamIn } from '../generated/proto/kalix/component/view/ViewStreamIn';

export { ViewStreamOut as StreamOut } from '../generated/proto/kalix/component/view/ViewStreamOut';
